import 'package:flutter/material.dart';
import 'package:code_test/lang.dart';

import '../utils.dart';

class ThirdTest extends StatefulWidget {
  const ThirdTest._();

  static Widget provideRoute() {
    return const ThirdTest._();
  }

  @override
  State<ThirdTest> createState() => _ThirdTestState();
}

class _ThirdTestState extends State<ThirdTest> {
  final String reallyLongLoremIpsum =
  """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse potenti nullam ac tortor vitae purus faucibus. Enim sed faucibus turpis in eu mi bibendum. Pharetra et ultrices neque ornare aenean euismod. Dolor morbi non arcu risus quis varius quam quisque id. Velit ut tortor pretium viverra. Enim eu turpis egestas pretium aenean pharetra magna ac. Consectetur a erat nam at lectus urna duis convallis convallis. Velit sed ullamcorper morbi tincidunt ornare massa eget. Tellus mauris a diam maecenas sed enim. Faucibus ornare suspendisse sed nisi lacus. Tellus elementum sagittis vitae et. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Tortor consequat id porta nibh venenatis cras sed. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Quam vulputate dignissim suspendisse in est ante in. Justo nec ultrices dui sapien eget mi proin sed. Adipiscing elit pellentesque habitant morbi. Ultricies integer quis auctor elit sed vulputate mi sit amet.

Quisque non tellus orci ac auctor augue. Congue mauris rhoncus aenean vel. Amet justo donec enim diam vulputate. Molestie at elementum eu facilisis sed odio morbi quis. Imperdiet sed euismod nisi porta lorem mollis aliquam. Etiam erat velit scelerisque in dictum. Nec nam aliquam sem et tortor consequat id porta nibh. Placerat in egestas erat imperdiet sed euismod nisi. Lacus viverra vitae congue eu consequat. Non sodales neque sodales ut etiam sit amet nisl purus.

Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. In nibh mauris cursus mattis molestie a iaculis at. Id interdum velit laoreet id donec ultrices tincidunt. Eu consequat ac felis donec et odio pellentesque diam volutpat. At varius vel pharetra vel turpis nunc eget lorem. Proin libero nunc consequat interdum varius sit. Et netus et malesuada fames ac turpis. Ac felis donec et odio pellentesque diam volutpat commodo. Sed viverra ipsum nunc aliquet bibendum enim. Elit duis tristique sollicitudin nibh sit amet. Ut aliquam purus sit amet luctus venenatis lectus magna. Adipiscing bibendum est ultricies integer quis auctor. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Eget lorem dolor sed viverra ipsum. Lectus arcu bibendum at varius vel. Consectetur adipiscing elit ut aliquam. Tortor condimentum lacinia quis vel eros donec ac. Ultricies integer quis auctor elit sed vulputate mi sit amet. Feugiat in fermentum posuere urna.

Tellus at urna condimentum mattis pellentesque id nibh tortor. Nec feugiat nisl pretium fusce. Nunc vel risus commodo viverra. Mi eget mauris pharetra et ultrices. Eget velit aliquet sagittis id consectetur. Quam elementum pulvinar etiam non quam lacus. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Arcu vitae elementum curabitur vitae nunc. Massa massa ultricies mi quis hendrerit. Dignissim diam quis enim lobortis.

Arcu bibendum at varius vel pharetra. Tortor at risus viverra adipiscing at. Donec pretium vulputate sapien nec sagittis aliquam malesuada. Donec enim diam vulputate ut pharetra sit amet aliquam. Eros donec ac odio tempor orci dapibus ultrices. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Nunc sed id semper risus in hendrerit gravida. Neque aliquam vestibulum morbi blandit cursus risus at ultrices mi. Sit amet commodo nulla facilisi nullam vehicula ipsum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Hendrerit gravida rutrum quisque non tellus. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis.

Condimentum id venenatis a condimentum vitae. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Sapien et ligula ullamcorper malesuada proin libero. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Integer quis auctor elit sed. Orci eu lobortis elementum nibh tellus molestie nunc. In hendrerit gravida rutrum quisque. Sit amet nulla facilisi morbi. Turpis massa sed elementum tempus. Viverra aliquet eget sit amet tellus. Aliquam sem et tortor consequat id porta nibh venenatis. Risus nullam eget felis eget. Sed enim ut sem viverra aliquet eget sit amet tellus.

Enim diam vulputate ut pharetra. Tellus orci ac auctor augue mauris augue neque gravida in. Habitant morbi tristique senectus et netus et. Nunc faucibus a pellentesque sit amet porttitor. Consectetur adipiscing elit pellentesque habitant morbi tristique. Morbi tincidunt augue interdum velit euismod. Aliquet nibh praesent tristique magna sit amet. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Convallis convallis tellus id interdum velit laoreet id donec ultrices. Arcu bibendum at varius vel pharetra vel. Nullam non nisi est sit amet facilisis magna etiam. Imperdiet proin fermentum leo vel orci. Quam lacus suspendisse faucibus interdum. Tristique nulla aliquet enim tortor at. Enim tortor at auctor urna nunc id cursus metus aliquam. Felis imperdiet proin fermentum leo vel.

Ac tortor vitae purus faucibus ornare. Aliquet nec ullamcorper sit amet risus nullam. Amet porttitor eget dolor morbi. Nulla facilisi etiam dignissim diam quis enim lobortis. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Quam pellentesque nec nam aliquam sem. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed. Diam vulputate ut pharetra sit amet aliquam id. Viverra tellus in hac habitasse platea dictumst vestibulum. Magna fermentum iaculis eu non diam phasellus vestibulum lorem. Urna et pharetra pharetra massa massa ultricies mi. Quam vulputate dignissim suspendisse in. Dignissim sodales ut eu sem integer vitae justo eget magna. Diam quam nulla porttitor massa id neque aliquam. Sed faucibus turpis in eu. Facilisi cras fermentum odio eu.

Eget duis at tellus at urna. Habitant morbi tristique senectus et netus. Euismod elementum nisi quis eleifend quam. Accumsan sit amet nulla facilisi morbi tempus. Tincidunt augue interdum velit euismod in pellentesque massa. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Arcu odio ut sem nulla pharetra diam sit amet nisl. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Nisi scelerisque eu ultrices vitae auctor eu. Id faucibus nisl tincidunt eget nullam non nisi est. Ac felis donec et odio pellentesque diam.

Eget egestas purus viverra accumsan in nisl. In est ante in nibh mauris cursus mattis molestie. Feugiat nibh sed pulvinar proin gravida hendrerit. Felis donec et odio pellentesque diam. Tempor nec feugiat nisl pretium fusce id velit ut tortor. Proin libero nunc consequat interdum varius. A diam sollicitudin tempor id eu. Viverra ipsum nunc aliquet bibendum enim. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Pellentesque habitant morbi tristique senectus. Amet mattis vulputate enim nulla aliquet. Non pulvinar neque laoreet suspendisse interdum consectetur. Nibh praesent tristique magna sit. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae.

Viverra tellus in hac habitasse platea dictumst vestibulum. Morbi tristique senectus et netus et. At in tellus integer feugiat scelerisque varius morbi enim. Dignissim diam quis enim lobortis scelerisque fermentum. Nunc sed id semper risus in. Urna condimentum mattis pellentesque id nibh tortor. Lorem ipsum dolor sit amet consectetur adipiscing elit. Risus feugiat in ante metus dictum at tempor. Odio pellentesque diam volutpat commodo sed egestas egestas. Elementum nibh tellus molestie nunc. Hendrerit dolor magna eget est lorem ipsum dolor sit. In tellus integer feugiat scelerisque varius morbi. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Et leo duis ut diam. Pharetra magna ac placerat vestibulum lectus. In mollis nunc sed id semper. Morbi tincidunt augue interdum velit euismod in.

Ornare aenean euismod elementum nisi. Etiam non quam lacus suspendisse faucibus interdum. Tortor consequat id porta nibh venenatis cras sed felis. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Imperdiet nulla malesuada pellentesque elit eget. Vitae congue eu consequat ac felis donec et odio. Enim eu turpis egestas pretium aenean pharetra magna. Sit amet porttitor eget dolor morbi non arcu risus quis. Eget dolor morbi non arcu risus quis varius. Sapien et ligula ullamcorper malesuada proin libero nunc. Semper risus in hendrerit gravida rutrum quisque non tellus. Urna neque viverra justo nec ultrices dui. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Enim neque volutpat ac tincidunt vitae semper quis lectus. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Maecenas volutpat blandit aliquam etiam erat. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Venenatis cras sed felis eget velit aliquet sagittis id. Eu augue ut lectus arcu bibendum at varius vel pharetra.

Pharetra magna ac placerat vestibulum lectus. Adipiscing elit pellentesque habitant morbi tristique senectus. Nisl nisi scelerisque eu ultrices vitae auctor. Tempor orci dapibus ultrices in. Convallis convallis tellus id interdum. Elementum facilisis leo vel fringilla est ullamcorper. Tellus pellentesque eu tincidunt tortor aliquam nulla. Sed vulputate odio ut enim blandit volutpat maecenas. Morbi tincidunt ornare massa eget egestas purus. Risus in hendrerit gravida rutrum quisque.

Ut faucibus pulvinar elementum integer enim. Et egestas quis ipsum suspendisse ultrices gravida dictum. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Dictum varius duis at consectetur lorem. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Duis convallis convallis tellus id interdum velit laoreet. Convallis aenean et tortor at risus viverra adipiscing at. Vulputate ut pharetra sit amet aliquam id diam. Eu scelerisque felis imperdiet proin fermentum leo vel. Et malesuada fames ac turpis egestas sed tempus urna. Est placerat in egestas erat. Lorem ipsum dolor sit amet consectetur. Nulla facilisi cras fermentum odio eu. Interdum velit laoreet id donec ultrices. Tortor dignissim convallis aenean et tortor at risus viverra. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Ac auctor augue mauris augue neque gravida in fermentum.

Amet massa vitae tortor condimentum lacinia quis vel. Congue nisi vitae suscipit tellus mauris a diam. Tellus cras adipiscing enim eu turpis. Id diam vel quam elementum pulvinar etiam non quam. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Sagittis purus sit amet volutpat consequat mauris nunc. Cursus turpis massa tincidunt dui ut ornare. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Orci a scelerisque purus semper eget duis at. Ultricies leo integer malesuada nunc vel risus commodo. Nam aliquam sem et tortor.

Amet consectetur adipiscing elit ut. Quis enim lobortis scelerisque fermentum dui faucibus in. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Viverra nibh cras pulvinar mattis nunc sed. Auctor augue mauris augue neque gravida in fermentum. Pharetra et ultrices neque ornare aenean euismod. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Nibh praesent tristique magna sit amet purus gravida quis. Ac turpis egestas integer eget. Diam vulputate ut pharetra sit. Dignissim sodales ut eu sem integer. Turpis egestas sed tempus urna et pharetra pharetra. Augue lacus viverra vitae congue eu consequat. Commodo quis imperdiet massa tincidunt nunc pulvinar. Nunc sed velit dignissim sodales ut eu. Scelerisque varius morbi enim nunc faucibus a pellentesque sit.

Quam adipiscing vitae proin sagittis nisl. Quis vel eros donec ac odio. Suspendisse sed nisi lacus sed viverra tellus in. Vulputate odio ut enim blandit volutpat maecenas volutpat. Elementum nisi quis eleifend quam. Sit amet cursus sit amet dictum. Et malesuada fames ac turpis egestas integer eget. Lorem dolor sed viverra ipsum nunc aliquet. Sed egestas egestas fringilla phasellus faucibus. Consectetur lorem donec massa sapien faucibus et molestie. Turpis nunc eget lorem dolor sed viverra ipsum. Mauris ultrices eros in cursus turpis massa tincidunt. Turpis egestas integer eget aliquet.

Tristique magna sit amet purus. Bibendum enim facilisis gravida neque convallis a cras semper. Mattis vulputate enim nulla aliquet porttitor lacus. A scelerisque purus semper eget duis at tellus at. Sodales neque sodales ut etiam sit amet nisl purus. Sit amet purus gravida quis blandit turpis cursus in hac. Cursus risus at ultrices mi tempus imperdiet nulla. Nulla at volutpat diam ut venenatis tellus in. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Semper quis lectus nulla at volutpat diam ut.

Erat pellentesque adipiscing commodo elit. Platea dictumst quisque sagittis purus sit amet. Quis enim lobortis scelerisque fermentum dui faucibus. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Fringilla urna porttitor rhoncus dolor purus non enim. Pretium vulputate sapien nec sagittis aliquam. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Nunc non blandit massa enim nec dui nunc mattis enim. Convallis tellus id interdum velit laoreet id. Cras semper auctor neque vitae tempus quam. Senectus et netus et malesuada fames ac turpis. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Non arcu risus quis varius quam quisque id diam. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Feugiat in fermentum posuere urna nec tincidunt. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sem integer vitae justo eget magna fermentum iaculis eu.

In est ante in nibh mauris. Non odio euismod lacinia at. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Ullamcorper morbi tincidunt ornare massa eget egestas. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Sed odio morbi quis commodo odio. Volutpat consequat mauris nunc congue nisi vitae suscipit.

Est ullamcorper eget nulla facilisi etiam. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Tortor id aliquet lectus proin nibh. Orci phasellus egestas tellus rutrum tellus. Sit amet justo donec enim diam vulputate ut. Adipiscing at in tellus integer feugiat scelerisque. Sapien nec sagittis aliquam malesuada. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Amet dictum sit amet justo donec enim diam vulputate ut. Congue quisque egestas diam in arcu cursus euismod.

Etiam non quam lacus suspendisse. Euismod in pellentesque massa placerat duis ultricies lacus sed. Odio aenean sed adipiscing diam donec adipiscing tristique. Urna nec tincidunt praesent semper feugiat nibh sed. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Cursus sit amet dictum sit amet justo donec. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Duis at tellus at urna. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Felis eget velit aliquet sagittis id consectetur purus. A pellentesque sit amet porttitor. Et malesuada fames ac turpis egestas maecenas. Pretium viverra suspendisse potenti nullam ac tortor vitae. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Eget nunc scelerisque viverra mauris in aliquam. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Leo in vitae turpis massa sed elementum tempus egestas sed. Vitae turpis massa sed elementum tempus egestas. Tincidunt eget nullam non nisi est. Pharetra et ultrices neque ornare aenean euismod.

Arcu vitae elementum curabitur vitae nunc. Gravida rutrum quisque non tellus orci ac auctor. Ultrices vitae auctor eu augue ut lectus arcu. Pretium lectus quam id leo in vitae. Donec et odio pellentesque diam volutpat commodo sed. Tempus iaculis urna id volutpat lacus. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Sit amet nulla facilisi morbi tempus iaculis urna id. Lacus laoreet non curabitur gravida. Sed turpis tincidunt id aliquet risus feugiat in ante.

Accumsan sit amet nulla facilisi morbi tempus. Vulputate mi sit amet mauris commodo. Pellentesque massa placerat duis ultricies lacus sed. Pulvinar elementum integer enim neque volutpat. Viverra adipiscing at in tellus integer feugiat scelerisque. Eros donec ac odio tempor. Blandit turpis cursus in hac habitasse platea dictumst. Massa enim nec dui nunc mattis enim ut tellus. Ullamcorper dignissim cras tincidunt lobortis. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Sem et tortor consequat id. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Praesent semper feugiat nibh sed pulvinar. Pellentesque massa placerat duis ultricies lacus sed. Neque gravida in fermentum et sollicitudin ac.

Sed tempus urna et pharetra pharetra massa massa ultricies mi. Egestas dui id ornare arcu odio. Morbi tincidunt augue interdum velit euismod in pellentesque. Sapien nec sagittis aliquam malesuada bibendum arcu. Quis lectus nulla at volutpat diam ut venenatis tellus. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Id cursus metus aliquam eleifend. Nunc eget lorem dolor sed. Cursus vitae congue mauris rhoncus aenean vel. Odio eu feugiat pretium nibh ipsum.

At in tellus integer feugiat scelerisque. Tristique senectus et netus et malesuada. Facilisis leo vel fringilla est. Facilisis volutpat est velit egestas dui id ornare arcu odio. Adipiscing elit pellentesque habitant morbi. At in tellus integer feugiat scelerisque varius morbi enim nunc. Massa tempor nec feugiat nisl pretium fusce id velit. Sed felis eget velit aliquet sagittis. Lacus laoreet non curabitur gravida arcu. Vitae congue mauris rhoncus aenean. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Ac turpis egestas maecenas pharetra convallis posuere morbi. Venenatis tellus in metus vulputate eu scelerisque. Nulla posuere sollicitudin aliquam ultrices sagittis. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem.

Platea dictumst quisque sagittis purus sit. Nunc id cursus metus aliquam eleifend mi in. Commodo nulla facilisi nullam vehicula ipsum a arcu. Porttitor lacus luctus accumsan tortor posuere ac. Eget nullam non nisi est sit amet facilisis magna. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Ipsum dolor sit amet consectetur adipiscing elit. Amet purus gravida quis blandit turpis cursus in hac. Amet dictum sit amet justo donec enim. Curabitur gravida arcu ac tortor dignissim convallis aenean. Dictum sit amet justo donec. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Ac ut consequat semper viverra. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Ante in nibh mauris cursus mattis molestie. Nisl rhoncus mattis rhoncus urna. Sem viverra aliquet eget sit amet.

Non nisi est sit amet facilisis. Amet mauris commodo quis imperdiet massa. Eget aliquet nibh praesent tristique magna sit. Adipiscing elit ut aliquam purus sit amet luctus. Scelerisque fermentum dui faucibus in ornare quam viverra. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Velit euismod in pellentesque massa placerat. Quis lectus nulla at volutpat diam ut venenatis tellus. Consectetur a erat nam at lectus. Cursus mattis molestie a iaculis at erat pellentesque. Lectus urna duis convallis convallis tellus id interdum. Lorem ipsum dolor sit amet consectetur. Cras semper auctor neque vitae tempus. Non quam lacus suspendisse faucibus interdum. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh.

Semper viverra nam libero justo laoreet sit amet. Tellus in metus vulputate eu. Morbi tincidunt augue interdum velit euismod in pellentesque. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Porta nibh venenatis cras sed felis. Euismod elementum nisi quis eleifend. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Est lorem ipsum dolor sit amet consectetur adipiscing elit. Volutpat blandit aliquam etiam erat velit scelerisque in. Turpis egestas sed tempus urna et pharetra pharetra massa. Ut placerat orci nulla pellentesque dignissim enim sit. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Posuere ac ut consequat semper.

Lobortis feugiat vivamus at augue eget arcu dictum. Dui ut ornare lectus sit amet. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Varius duis at consectetur lorem donec massa sapien faucibus. Augue eget arcu dictum varius duis at consectetur lorem. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Id velit ut tortor pretium. Lacus luctus accumsan tortor posuere ac ut consequat semper. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Amet cursus sit amet dictum. Id diam vel quam elementum. Arcu dui vivamus arcu felis. Aenean pharetra magna ac placerat vestibulum lectus. Vel facilisis volutpat est velit egestas dui. Placerat duis ultricies lacus sed turpis tincidunt. Velit laoreet id donec ultrices tincidunt arcu.

Volutpat blandit aliquam etiam erat velit scelerisque in. Amet massa vitae tortor condimentum lacinia quis. Facilisis mauris sit amet massa vitae tortor condimentum. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Morbi tristique senectus et netus et. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Mi ipsum faucibus vitae aliquet nec ullamcorper. Consectetur adipiscing elit ut aliquam. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Nullam vehicula ipsum a arcu cursus.

Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Egestas sed sed risus pretium quam vulputate dignissim. Egestas congue quisque egestas diam in arcu cursus. Aenean pharetra magna ac placerat. Scelerisque eleifend donec pretium vulputate sapien. Velit dignissim sodales ut eu sem integer vitae. Est ultricies integer quis auctor elit sed vulputate mi sit. A cras semper auctor neque vitae tempus. Diam vulputate ut pharetra sit. Et tortor at risus viverra adipiscing at in. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis.

Cras pulvinar mattis nunc sed. Pellentesque diam volutpat commodo sed egestas. Eget nunc lobortis mattis aliquam faucibus purus in massa. Id faucibus nisl tincidunt eget nullam non nisi est. Egestas congue quisque egestas diam in arcu cursus euismod. Ut enim blandit volutpat maecenas volutpat blandit. Natoque penatibus et magnis dis parturient. Porttitor eget dolor morbi non arcu risus. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Tortor id aliquet lectus proin nibh nisl condimentum id venenatis. Massa vitae tortor condimentum lacinia quis. Auctor eu augue ut lectus arcu. Molestie ac feugiat sed lectus. Sed risus pretium quam vulputate dignissim suspendisse.

Nam libero justo laoreet sit amet cursus sit amet. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Id leo in vitae turpis. Sed vulputate mi sit amet mauris commodo quis imperdiet. Varius quam quisque id diam vel. Tincidunt vitae semper quis lectus nulla at volutpat. Nunc lobortis mattis aliquam faucibus purus in massa. Et malesuada fames ac turpis egestas sed tempus urna. Diam maecenas sed enim ut sem viverra aliquet. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Eu scelerisque felis imperdiet proin fermentum leo vel. Interdum velit euismod in pellentesque massa placerat duis ultricies.

Sit amet justo donec enim diam vulputate ut pharetra sit. Nec nam aliquam sem et tortor. Ut venenatis tellus in metus vulputate eu. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. In dictum non consectetur a. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Odio morbi quis commodo odio aenean sed adipiscing diam. Tortor aliquam nulla facilisi cras fermentum. Erat nam at lectus urna duis convallis convallis. Urna porttitor rhoncus dolor purus non enim praesent elementum. Duis ut diam quam nulla porttitor massa id. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Sit amet nisl suscipit adipiscing bibendum est. Egestas congue quisque egestas diam in arcu cursus euismod. Augue ut lectus arcu bibendum at varius vel pharetra.

Gravida neque convallis a cras. Semper quis lectus nulla at volutpat. Eu tincidunt tortor aliquam nulla facilisi cras. Id nibh tortor id aliquet lectus. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Amet purus gravida quis blandit turpis cursus in hac. Vitae justo eget magna fermentum iaculis. Senectus et netus et malesuada fames ac turpis egestas. Egestas sed tempus urna et pharetra. Ut tristique et egestas quis ipsum suspendisse ultrices. Ultrices dui sapien eget mi. Vel orci porta non pulvinar neque laoreet suspendisse. Turpis nunc eget lorem dolor sed viverra ipsum. Aliquam sem et tortor consequat id porta nibh venenatis cras. Tempus imperdiet nulla malesuada pellentesque.

Tellus in hac habitasse platea dictumst vestibulum. Non sodales neque sodales ut etiam sit. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Ipsum consequat nisl vel pretium lectus quam id leo in. Sodales ut eu sem integer vitae. Quam viverra orci sagittis eu. Pellentesque eu tincidunt tortor aliquam nulla. Tortor condimentum lacinia quis vel. Id venenatis a condimentum vitae sapien pellentesque habitant. Eget mi proin sed libero enim sed. Porttitor leo a diam sollicitudin tempor id eu. Nec ullamcorper sit amet risus nullam. Sed felis eget velit aliquet. Semper risus in hendrerit gravida rutrum. Nibh tellus molestie nunc non blandit massa. Dui id ornare arcu odio ut sem.

Posuere ac ut consequat semper viverra nam libero justo. Luctus accumsan tortor posuere ac ut consequat. Nec feugiat in fermentum posuere urna. Semper feugiat nibh sed pulvinar proin gravida. Duis ultricies lacus sed turpis tincidunt. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Odio ut sem nulla pharetra diam. Magna fermentum iaculis eu non diam phasellus. Id faucibus nisl tincidunt eget. Massa tincidunt nunc pulvinar sapien et ligula. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Praesent tristique magna sit amet purus gravida quis blandit turpis. Nunc sed augue lacus viverra vitae congue.

Tellus orci ac auctor augue mauris augue neque gravida. Tempor orci eu lobortis elementum nibh. Semper auctor neque vitae tempus quam. Sollicitudin ac orci phasellus egestas tellus rutrum. Ornare arcu odio ut sem nulla pharetra diam. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Amet mattis vulputate enim nulla aliquet. Quis viverra nibh cras pulvinar. Faucibus nisl tincidunt eget nullam non nisi est sit. Vel turpis nunc eget lorem dolor sed. Non enim praesent elementum facilisis leo vel fringilla. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Tellus orci ac auctor augue. Eget lorem dolor sed viverra.

Tempor id eu nisl nunc mi ipsum. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Orci a scelerisque purus semper eget duis at tellus at. At lectus urna duis convallis convallis. Nec nam aliquam sem et. Arcu risus quis varius quam quisque id diam vel. At lectus urna duis convallis. Tincidunt arcu non sodales neque. Turpis massa sed elementum tempus. Congue quisque egestas diam in arcu cursus. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Dolor sed viverra ipsum nunc aliquet bibendum. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Eget lorem dolor sed viverra.

Urna nec tincidunt praesent semper feugiat nibh. Ullamcorper eget nulla facilisi etiam dignissim diam. In hac habitasse platea dictumst quisque sagittis purus sit amet. Risus at ultrices mi tempus imperdiet. Senectus et netus et malesuada fames ac turpis egestas. Eu scelerisque felis imperdiet proin fermentum leo. Posuere morbi leo urna molestie at elementum. Arcu dictum varius duis at consectetur lorem donec. Mauris vitae ultricies leo integer malesuada nunc. Aliquam ut porttitor leo a diam sollicitudin tempor id. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Morbi non arcu risus quis varius quam quisque id. Sollicitudin tempor id eu nisl nunc. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Velit euismod in pellentesque massa. Integer vitae justo eget magna fermentum. Mauris sit amet massa vitae tortor condimentum lacinia quis vel.

Ultricies tristique nulla aliquet enim tortor at auctor urna. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Purus semper eget duis at. Quam quisque id diam vel quam elementum pulvinar etiam non. Amet risus nullam eget felis eget. Sagittis orci a scelerisque purus. Nisi porta lorem mollis aliquam ut porttitor leo. In hac habitasse platea dictumst. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Ullamcorper eget nulla facilisi etiam dignissim. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Pulvinar proin gravida hendrerit lectus a. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor. Nunc sed velit dignissim sodales ut eu.

Natoque penatibus et magnis dis parturient montes nascetur. Sed sed risus pretium quam vulputate dignissim suspendisse in. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Fermentum posuere urna nec tincidunt. Volutpat lacus laoreet non curabitur gravida arcu. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Fermentum odio eu feugiat pretium nibh ipsum. Fusce ut placerat orci nulla pellentesque dignissim. Quisque id diam vel quam elementum pulvinar etiam non quam. Non pulvinar neque laoreet suspendisse interdum consectetur. Ornare arcu odio ut sem nulla pharetra diam sit. Dui id ornare arcu odio ut sem nulla pharetra diam. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. In nibh mauris cursus mattis molestie. Pretium aenean pharetra magna ac placerat vestibulum lectus. Nibh praesent tristique magna sit amet purus gravida. Tristique et egestas quis ipsum suspendisse. Ornare arcu dui vivamus arcu felis bibendum.

Enim sed faucibus turpis in eu mi bibendum. Duis ultricies lacus sed turpis tincidunt. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Augue interdum velit euismod in pellentesque massa placerat. Et netus et malesuada fames ac turpis egestas integer. Id venenatis a condimentum vitae sapien. Pretium aenean pharetra magna ac placerat vestibulum. Risus at ultrices mi tempus. Rutrum quisque non tellus orci ac auctor. Phasellus egestas tellus rutrum tellus. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Massa tincidunt dui ut ornare lectus sit. Magna fringilla urna porttitor rhoncus dolor. Faucibus ornare suspendisse sed nisi lacus. Id velit ut tortor pretium. Tortor aliquam nulla facilisi cras fermentum odio. Nibh venenatis cras sed felis eget velit aliquet sagittis id. Sed felis eget velit aliquet sagittis id consectetur purus. Dignissim suspendisse in est ante in. Risus commodo viverra maecenas accumsan lacus vel.

Nulla aliquet enim tortor at. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Turpis massa sed elementum tempus. Pellentesque habitant morbi tristique senectus et. Cras ornare arcu dui vivamus arcu felis. Tellus mauris a diam maecenas sed enim ut sem viverra. Amet purus gravida quis blandit turpis cursus in. Sagittis nisl rhoncus mattis rhoncus urna. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Egestas diam in arcu cursus euismod quis viverra. Ornare massa eget egestas purus viverra accumsan in. Vel elit scelerisque mauris pellentesque. Tortor consequat id porta nibh venenatis cras sed. Posuere urna nec tincidunt praesent semper. Risus nullam eget felis eget nunc lobortis mattis.

Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Auctor eu augue ut lectus arcu bibendum at varius. Facilisis gravida neque convallis a cras semper auctor neque. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. At volutpat diam ut venenatis tellus in. Ut etiam sit amet nisl. Tincidunt vitae semper quis lectus nulla. Risus at ultrices mi tempus imperdiet. In hendrerit gravida rutrum quisque non tellus orci. Libero nunc consequat interdum varius sit amet. Id velit ut tortor pretium viverra suspendisse potenti nullam. Elementum curabitur vitae nunc sed velit dignissim. Cursus euismod quis viverra nibh. Morbi quis commodo odio aenean sed adipiscing.

Eu feugiat pretium nibh ipsum consequat nisl vel. Fames ac turpis egestas maecenas pharetra convallis. Gravida neque convallis a cras semper auctor. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Laoreet id donec ultrices tincidunt arcu non. Leo vel orci porta non pulvinar neque. Leo vel fringilla est ullamcorper eget. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Id leo in vitae turpis massa. Amet nisl suscipit adipiscing bibendum. Ultrices neque ornare aenean euismod. Egestas sed tempus urna et. Ultricies tristique nulla aliquet enim tortor at. In hac habitasse platea dictumst vestibulum rhoncus. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis.

Praesent tristique magna sit amet purus gravida. Augue lacus viverra vitae congue eu consequat ac felis donec. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Viverra justo nec ultrices dui sapien eget mi proin. Fames ac turpis egestas integer eget. Gravida quis blandit turpis cursus in. Commodo elit at imperdiet dui accumsan sit amet. Non tellus orci ac auctor augue. Felis bibendum ut tristique et egestas quis ipsum suspendisse. At consectetur lorem donec massa sapien faucibus et. Elementum pulvinar etiam non quam lacus suspendisse. Sagittis aliquam malesuada bibendum arcu. Lectus quam id leo in vitae turpis. Tellus at urna condimentum mattis pellentesque. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Vel pharetra vel turpis nunc eget lorem dolor sed. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Libero enim sed faucibus turpis in eu mi bibendum. Diam vel quam elementum pulvinar.

Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ac odio tempor orci dapibus ultrices. Neque sodales ut etiam sit amet nisl purus in mollis. Quis lectus nulla at volutpat diam ut. Ut placerat orci nulla pellentesque dignissim enim sit amet. Fermentum posuere urna nec tincidunt praesent semper. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Eget nunc scelerisque viverra mauris. Tortor consequat id porta nibh. Faucibus nisl tincidunt eget nullam non nisi est sit. Neque sodales ut etiam sit amet. Nunc id cursus metus aliquam eleifend mi in. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Tristique senectus et netus et malesuada fames ac turpis egestas. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. In ante metus dictum at tempor commodo ullamcorper. Velit egestas dui id ornare arcu odio ut sem nulla.

Fusce ut placerat orci nulla pellentesque. Non diam phasellus vestibulum lorem sed risus ultricies tristique. Sit amet tellus cras adipiscing enim eu. Suscipit adipiscing bibendum est ultricies integer quis auctor elit. Cras adipiscing enim eu turpis. Orci eu lobortis elementum nibh tellus. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Urna id volutpat lacus laoreet non. In hendrerit gravida rutrum quisque. Aliquam etiam erat velit scelerisque in dictum. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique.""";
  final GlobalKey _textKey = GlobalKey();
  final TextStyle textStyle = const TextStyle(fontSize: 16);

  void getSizeBeforeBuild() {
    final size = getTextSizeBeforeBuild(reallyLongLoremIpsum, textStyle, MediaQuery.of(context).size.width - 48); // considering padding
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        content: Text("${currentLanguage.translate('beforeBuild:')} $size"),
      ),
    );

  }

  void getSizeAfterBuild() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final box = _textKey.currentContext?.findRenderObject() as RenderBox?;
      if (box != null) {
        showDialog(
          context: context,
          builder: (_) => AlertDialog(
            content: Text("${currentLanguage.translate('afterBuild:')} ${box.size}"),
          ),
        );

      }
    });
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(currentLanguage.translate("thirdTest")),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            children: [
              Text(
                currentLanguage.translate("thirdTestIntroduction"),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 16),
              SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Row(
                  children: [
                    ElevatedButton(
                      onPressed: getSizeBeforeBuild,
                      child: Text(currentLanguage.translate("getSizeBeforeBuild")),
                    ),
                    const SizedBox(width: 16),
                    ElevatedButton(
                      onPressed: getSizeAfterBuild,
                      child: Text(currentLanguage.translate("getSizeAfterBuild")),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),
              Expanded(
                child: SingleChildScrollView(
                  child: Text(
                    key: _textKey,
                    reallyLongLoremIpsum,
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}


